# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . /usr/src/app

# Install Flask and Flask-RESTful
RUN pip install Flask Flask-RESTful

# Expose the port on which your Flask app will run
EXPOSE 80

# Specify the command to run on container start
CMD ["python", "api.py"]
